before move logs to ~/.smartSlurm

diff --git a/bin/ssbatch b/bin/ssbatch
--- a/bin/ssbatch
+++ b/bin/ssbatch
@@ -330,27 +330,37 @@ if [[ ! -z "$logDir" && "$testRun" == "run" ]]; then
         #ls -l $flagDir/ 1>&2 
     elif [ -f logs/keepRunningJobs.txt ]; then 
      
-        set -x    
+        #set -x    
         #cat logs/allJobs.txt >&2
 
         #echo $flag >&2
         # check the third column for the job name, then find the the job id in column 1
         id=`cat logs/allJobs.txt | awk '{if ($3 ~ /'"$flag/"') print $1;}' | tail -n 1`
         
-        # job still running
-        if [ ! -z "$id" ] && grep ^$id logs/keepRunningJobs.txt; then 
+    
+        if [ ! -z "$id" ]; then   
             
+            # need re-run because it has upsteam needs to run 
             if [ ! -z "$deps" ]; then 
+                #still runing, kill it
+                grep ^$id logs/keepRunningJobs.txt 2>/dev/null && scancel $id 
                 echo $deps
-                dep=`grep ^$id logs/keepRunningJobs.txt | awk -d' ' -f2`
-                echo should add to the job $dep
-                [[ "$dep" != "null" ]] && deps=$deps:$dep
-                scancel $id
+                # check if the upseam jobs still running
+                dep=`grep ^$id logs/keepRunningJobs.txt 2>/dev/null | cut -d' ' -f2`
+                
+                if [[ "$dep" != "null" ]]; then 
+                    for t in ${dep//\./ }; do
+                        #still runnig, add to the dependency
+                        grep ^$t logs/keepRunningJobs.txt 2>/dev/null && deps=$deps:$t && depsO=$depsO.$t
+                    done
+                
+                fi 
+                
             else       
                 echo thisJobStillRunning && exit
             fi    
         fi
-        set +x 
+        #set +x 
     fi    
     #ls $flagDir/$flag.* 1>&2
     rm $flagDir/$flag.* 2>/dev/null || : # in case user has set -e and file not exist,  we will not exit
@@ -403,9 +413,9 @@ if [ -z "$deps" ] &&  [[ "$inputs" != "none" ]]; then
 
             #filter by software and reference
             # todo: maybe able to replace / in ref at begaining of the script?
-            ref1=${ref//\//-}
-            grep COMPLETED ~/smartSlurm/jobRecord.txt | awk -F"," -v a=$software -v b=$ref1 '{ if($12 == a && $13 == b) {print $2, $7 }}' | sort -r  -k1,1 -k2,2 | sort -u -k1,1 > $OUT/mem.txt
-            grep COMPLETED ~/smartSlurm/jobRecord.txt | awk -F"," -v a=$software -v b=$ref1 '{ if($12 == a && $13 == b) {print $2, $8 }}' | sort -r  -k1,1 -k2,2 | sort -u -k1,1 > $OUT/time.txt
+            ref=${ref//\//-}
+            grep COMPLETED ~/smartSlurm/jobRecord.txt 2>/dev/null | awk -F"," -v a=$software -v b=$ref '{ if($12 == a && $13 == b) {print $2, $7 }}' | sort -r  -k1,1 -k2,2 | sort -u -k1,1 > $OUT/mem.txt
+            grep COMPLETED ~/smartSlurm/jobRecord.txt 2>/dev/null | awk -F"," -v a=$software -v b=$ref '{ if($12 == a && $13 == b) {print $2, $8 }}' | sort -r  -k1,1 -k2,2 | sort -u -k1,1 > $OUT/time.txt
 
             echo "Got mem data from jobRecord.txt (content of mem.txt):"
             cat $OUT/mem.txt 
@@ -477,8 +487,8 @@ if [ -z "$deps" ] &&  [[ "$inputs" != "none" ]]; then
 elif [[ "$inputs" == "none" ]]; then
     ref=${ref//\//-}
     
-    rows=`( wc -l ~/smartSlurm/stats/$software.$ref.mem.stat.noInput 2>/dev/null || echo 0 ) | cut -f 1 -d " "`
-    
+    rows=`( wc -l ~/smartSlurm/stats/$software.$ref.mem.stat.noInput 2>/dev/null || echo 0 ) | awk '{print $1}'`
+    #echo rows  $rows >&2
     # empty or more than 60 minutes but less than 4 records
     if test `find ~/smartSlurm/stats/$software.$ref.mem.stat.noInput -mmin +60` && [ $rows -lt 3 ] || [ $rows -eq 0 ]; then  
         mkdir -p ~/smartSlurm/stats/
@@ -486,9 +496,9 @@ elif [[ "$inputs" == "none" ]]; then
         #test `find ~/smartSlurm/jobRecord.txt -mmin +20` && echo jobRecord.txt synced within 21 hour. No need to re-sync || cat $HOME/smartSlurm/myJobRecord.txt > ~/smartSlurm/jobRecord.txt  
 
         # todo: could use single file here
-        grep COMPLETED ~/smartSlurm/jobRecord.txt | awk -F, -v a=$software -v b=$ref '{ if($12 == a && $13 == b) {print $7 }}' > ~/smartSlurm/stats/$software.$ref.mem.stat.noInput
+        grep COMPLETED ~/smartSlurm/jobRecord.txt 2>/dev/null | awk -F, -v a=$software -v b=$ref '{ if($12 == a && $13 == b) {print $7 }}' > ~/smartSlurm/stats/$software.$ref.mem.stat.noInput
      
-        grep COMPLETED ~/smartSlurm/jobRecord.txt | awk -F, -v a=$software -v b=$ref '{ if($12 == a && $13 == b) {print $8 }}' > ~/smartSlurm/stats/$software.$ref.time.stat.noInput
+        grep COMPLETED ~/smartSlurm/jobRecord.txt 2>/dev/null | awk -F, -v a=$software -v b=$ref '{ if($12 == a && $13 == b) {print $8 }}' > ~/smartSlurm/stats/$software.$ref.time.stat.noInput
         
         if [ -s ~/smartSlurm/stats/$software.$ref.mem.stat.noInput ] && [ -s ~/smartSlurm/stats/$software.$ref.time.stat.noInput ]; then 
             
@@ -527,10 +537,10 @@ elif [[ "$inputs" == "none" ]]; then
         resAjust="$resAjust#Give ${extraMem}M extra memory and $extraMin more minutes. \n#So use this to submit the job: $mem  ${time}m"
         
     else 
-        resAjust="$resAjust#There are less than 3 job records. Use default mem and time. \n"
+        resAjust="$resAjust#There are less than 3 job records. Use default mem and time."
     fi
 else
-    echo No inputs.
+    resAjust="$resAjust#There is no input or input not available yet. Use default mem and time."
 fi
 
 echo
@@ -584,7 +594,7 @@ echo
 echo Building new sbatch command ... >&2
 #echo "#!/bin/bash" > $job 
 
-echo -e "#!/bin/bash\n$resAjust\n\ntrap \"{ cleanUp.sh \\\"$logDir\\\" \"$software\" \"${ref//\//-}\" \\\"$flag\\\" \"$inputSize\" \"$core\" \"$memO\" \"$timeO\" \"$mem\" \"$time\" \"$partition\"  \\\"${slurmAcc#*-A }\\\" \\\"$0 $@\\\"; }\" EXIT\n" > $job
+echo -e "#!/bin/bash\n$resAjust\n\ntrap \"{ cleanUp.sh \\\"$logDir\\\" \"$software\" \"${ref//\//-}\" \\\"$flag\\\" \"$inputSize\" \"$core\" \"$memO\" \"$timeO\" \"$mem\" \"$time\" \"$partition\"  \\\"${slurmAcc#*-A }\\\" \"$inputs\" \\\"$0 $@\\\"; }\" EXIT\n" > $job
 
 if [ -z "$slurmScript" ]; then 
     #echo "touch $startFlag" >> $job
@@ -623,7 +633,7 @@ fi
 if [ -z "$logDir" ]; then
     cmd="/usr/bin/sbatch --mail-type=FAIL --requeue --parsable -p $partition --mem $mem -t $time --open-mode=append $slurmAcc"
 else
-    cmd="/usr/bin/sbatch --mail-type=FAIL --requeue --parsable -p $partition --mem $mem -t $time --open-mode=append -o $outFlag -e $errFlag -J $flag $deps $slurmAcc"
+    cmd="/usr/bin/sbatch --mail-type=FAIL --requeue --parsable -p $partition --mem $mem -t $time --open-mode=append -o $outFlag -e $outFlag -J $flag $deps $slurmAcc"
     #rm $startFile $failFile $flag.failed $flag.killed # 2>/dev/null  || : 
 fi
 if [ -z "$slurmScript" ]; then 
