try checkpoint

diff --git a/bin/ssbatch b/bin/ssbatch
--- a/bin/ssbatch
+++ b/bin/ssbatch
@@ -601,7 +601,7 @@ fi
 #echoerr
 
 # for OOM testing
-mem=1412
+#mem=1412
 
 [ -z "$min" ] && { echoerr did not find time limit; exit 1; }
  
@@ -658,7 +658,7 @@ echoerr
 echoerr Building new sbatch command ... 
 #echo "#!/bin/bash" > $job   
 
-echo -e "#!/bin/bash\n\n\ntrap \"{ cleanUp.sh \\\"$logDir\\\" \"$software\" \"${ref//\//-}\" \\\"$flag\\\" \"$inputSize\" \"$core\" \"$memO\" \"$minO\" \"$mem\" \"$min\" \"$partition\"  \\\"${slurmAcc#*-A }\\\" \"$inputs\" \"$extraMem\"; }\" EXIT\njobMonitor.sh $flag $mem $min &\n" > $job
+echo -e "#!/bin/bash\nset -x\n\ntrap \"{ cleanUp.sh \\\"$logDir\\\" \"$software\" \"${ref//\//-}\" \\\"$flag\\\" \"$inputSize\" \"$core\" \"$memO\" \"$minO\" \"$mem\" \"$min\" \"$partition\"  \\\"${slurmAcc#*-A }\\\" \"$inputs\" \"$extraMem\"; }\" EXIT\njobMonitor.sh $flag $mem $min &\n" > $job
 
 # [[ "$mem" == *G ]] && totalM=$(( 1024 * ${mem%G})) || totalM=${mem%M}
 
@@ -678,9 +678,16 @@ echo -e "#!/bin/bash\n\n\ntrap \"{ cleanUp.sh \\\"$logDir\\\" \"$software\" \"${
 if [ -z "$slurmScript" ]; then 
     #echo "touch $startFlag" >> $job
     wrapCMD=`echo $wrapCMD | xargs echo -n`; wrapCMD=${wrapCMD%;} # remove ending space and ; from command
-    if which dmtcp_command >/dev/null 2>&1 && [ $mem -gt 5 ]; then
-        echo -e "set -x\ntrap \"[ -f $succFlag ] || touch $failFlag\" EXIT SIGSTOP SIGHUP\nsh -e -c \"$wrapCMD\" && touch $succFlag" > ${job%.sh}.cmd
-        echo "srun -n 1 $slurmAcc bash -e -c \"checkpoint.sh  \\\"sh ${job%.sh}.cmd\\\" $flag $mem $min $extraMem; \"" >> $job   
+    if which dmtcp_command >/dev/null 2>&1; then
+        #echo -e "set -x\ntrap \"[ -f $succFlag ] || touch $failFlag\" EXIT SIGSTOP SIGHUP\nsh -e -c \"$wrapCMD\" && touch $succFlag" > ${job%.sh}.cmd
+
+        echo -e "set -x\nps -u $USER\nsh -e -c \"$wrapCMD;\" &" > ${job%.sh}.cmd
+        echo -e "pid=\$$" >> ${job%.sh}.cmd
+        echo -e "echo \$pid > ${job%.sh}/taskProcessID.txt" >> ${job%.sh}.cmd
+        echo -e "ps -u $USER\nwait \$pid" >> ${job%.sh}.cmd
+        echo -e "echo \$? > ${job%.sh}/taskProcessStatus.txt" >> ${job%.sh}.cmd
+
+        echo "srun -n 1 $slurmAcc bash -e -c \"checkpoint.sh  \\\"sh ${job%.sh}.cmd\\\" $flag $mem $min $extraMem; \" && touch $succFlag" >> $job   
     else 
         echo "srun -n 1 $slurmAcc bash -e -c \"$wrapCMD; \" && touch $succFlag" >> $job 
     fi
