checkpiont

diff --git a/bin/ssbatch b/bin/ssbatch
--- a/bin/ssbatch
+++ b/bin/ssbatch
@@ -702,8 +702,8 @@ if [ -z "$slurmScript" ]; then
         # echo -e "ps -u $USER\nwait \$pid" >> ${job%.sh}.cmd
         # echo -e "echo \$? > ${job%.sh}/taskProcessStatus.txt" >> ${job%.sh}.cmd
 
-
-        echo -e "set -x\nps -fu $USER\nsh -e -o pipefail  -c \"$wrapCMD;\" &" > ${job%.sh}.cmd
+        # note: if job OOT or OOM, .success or .failed will not be created
+        echo -e "set -x\nps -fu $USER\nsh -e -o pipefail  -c \"$wrapCMD;\" && touch ${job%.sh}.success || touch ${job%.sh}.failed  &" > ${job%.sh}.cmd
         ##echo -e "x=\"\$wrapCMD\" >> ${job%.sh}.cmd
         ##echo -e "ps -fu $USER | grep -v awk | grep -v srun | grep -v grep | grep \"$flag\"" >> ${job%.sh}.cmd
         #echo -e "ps -fu $USER | grep \"log/$flag.cmd\"" >> ${job%.sh}.cmd
@@ -714,7 +714,7 @@ if [ -z "$slurmScript" ]; then
         #echo -e "pid=\`echo -e \"\$pss\" | head -n 4 | tail -n 1 | tr -s ' ' | cut -d' ' -f2\`" >> ${job%.sh}.cmd
         #echo -e "echo \$pid > ${job%.sh}/taskProcessID.txt" >> ${job%.sh}.cmd
         echo -e "ps -fu $USER\nwait" >> ${job%.sh}.cmd
-        echo -e "echo done > ${job%.sh}/taskProcessStatus.txt" >> ${job%.sh}.cmd
+        echo -e "echo done > ${job%.sh}.success" >> ${job%.sh}.cmd
 
 # x="bash -e -c \"set -e; sh sleeping1.sh; \""
 # pid=`ps -f -u $USER | grep -v awk | grep -v srun | awk -v pat="$x"  '$0 ~ pat { print $2 }' | tail -n 1`
