before add srun --mem

diff --git a/bin/ssbatch b/bin/ssbatch
--- a/bin/ssbatch
+++ b/bin/ssbatch
@@ -37,8 +37,8 @@
 #set -e
 #set -x 
 
-extraMin=20 # 500M. extra minutes than the estimated time
-extraMem=500  # 20min. extra memory than the estinated memory
+# extraMin=5 # 5min. extra minutes than the estimated time
+# extraMem=5  # 5M. extra memory than the estinated memory
 
 usage() { echo -e "Short Usage: \n${0##*/} [-L logDir (for smartPipline)]  [-S software] [-R reference] [-F uniqueJobFlag (for smartPieline)s] [-I inputList] [-D Dependencies (for smartPipeline)] [sbatch options] [run]\nDetail Detail Usage:\n${0##*/} [-L logDir, optional. Such as: ./], [-S software, optional. Such as: bowtie2-4core. If empty, use script name as software name] [-R reference, optional. Such as: hg19] [-F uniqueJobFlag, optional. Such as 1.bowtie.s1.fa] [-I inputFileOrFolderList, optional. Such as: read1.fq,read2.fq] [ -D dependent jobs] <regular sbatch options, optional. Such as: job.sh or -p short -c 1 -t 2:0:0 --mem 2G --wrap \"my_application para1 para2\"> [run, optional: run will submit job, empty will do a dry run without submitting a job.]"; exit 1; }
 
@@ -381,8 +381,70 @@ inputSize=0
 echo 
 echo Check if there input file list and this job does not depend on other jobs
 
+
+# do not have input file list    #todo: we can try to figure out the input from the software parameters here
+if [[ "$inputs" == "none" ]]; then
+    echo No inputs
+    resAjust="$resAjust#This job does not have input.\n"
+    ref=${ref//\//-}
+    
+    rows=`( wc -l $jobRecordDir/stats/$software.$ref.mem.stat.noInput 2>/dev/null || echo 0 ) | awk '{print $1}'`
+    #echo rows  $rows >&2
+    # empty or more than 60 minutes but less than 4 records
+    if test `find $jobRecordDir/stats/$software.$ref.mem.stat.noInput -mmin +60 2>/dev/null` && [ $rows -lt 3 ] || [ $rows -eq 0 ]; then  
+        mkdir -p $jobRecordDir/stats/
+        #cat /home/*/smartSlurm/stats/myJobRecord.txt > $jobRecordDir/stats/jobRecord.txt 
+        #test `find $jobRecordDir/jobRecord.txt -mmin +20` && echo jobRecord.txt synced within 21 hour. No need to re-sync || cat $HOME/smartSlurm/myJobRecord.txt > $jobRecordDir/jobRecord.txt  
+
+        # todo: could use single file here
+        grep COMPLETED $jobRecordDir/jobRecord.txt 2>/dev/null | awk -F, -v a=$software -v b=$ref '{ if($12 == a && $13 == b) {print $7 }}' > $jobRecordDir/stats/$software.$ref.mem.stat.noInput
+     
+        grep COMPLETED $jobRecordDir/jobRecord.txt 2>/dev/null | awk -F, -v a=$software -v b=$ref '{ if($12 == a && $13 == b) {print $8 }}' > $jobRecordDir/stats/$software.$ref.time.stat.noInput
+        
+        if [ -s $jobRecordDir/stats/$software.$ref.mem.stat.noInput ] && [ -s $jobRecordDir/stats/$software.$ref.time.stat.noInput ]; then 
+            
+            OUT="$(mktemp -d)"
+            paste $jobRecordDir/stats/$software.$ref.time.stat.noInput $jobRecordDir/stats/$software.$ref.mem.stat.noInput | column -s $'\t' -t | sed '$ d' > $jobRecordDir/stats/$software.$ref.timeMem.noInput.txt
+
+            cp $jobRecordDir/stats/$software.$ref.timeMem.noInput.txt $OUT/timeMem.txt
+            cd $OUT
+            # make plot and calculate statistics
+            gnuplot -e 'set term pdf; set output "timeMem.pdf"; set title "Time vs. Memory Usage" font "Helvetica Bold,18"; set xlabel "Time(Min)"; set ylabel "Memory(M)"; f(x)=a*x+b; fit f(x) "timeMem.txt" u 1:2 via a, b; t(a,b)=sprintf("f(x) = %.2fx + %.2f", a, b); plot "timeMem.txt" u 1:2,f(x) t t(a,b); print "Finala=", a; print "Finalb=",b; stats "timeMem.txt" u 1 ' 2>&1 | grep 'Final\| M' | awk 'NF<4{print $1, $2}' |sed 's/:/=/' | sed 's/ //g' > $software.$ref.timeMem.stat.noInput.txt
+
+            cd - 
+            convert $OUT/timeMem.pdf -background White -flatten $jobRecordDir/stats/$software.$ref.stat.noInput.pdf 2>/dev/null
+            pdftoppm $jobRecordDir/stats/$software.$ref.stat.noInput.pdf  -png > $jobRecordDir/stats/$software.$ref.stat.noInput.png 2>/dev/null
+            
+            rows=`{ wc -l $jobRecordDir/stats/$software.$ref.mem.stat.noInput 2>/dev/null || echo 0; } | cut -f 1 -d " "` 
+        
+            rm -r $OUT 2>/dev/null 
+        fi
+    fi
+
+    # at least 3 records
+    if [ $rows -gt 3 ]; then
+        cutoffRow=$(( ($row - 1)  / 10  + 1)) # top 10
+        
+        mem=`cat $jobRecordDir/stats/$software.$ref.mem.stat.noInput | sort -nr | tr '\n' ' ' | cut -f $cutoffRow -d " "`
+        mem=$((${mem/\.*/} + extraMem))M
+#       mem=${txt[$cutoffRow]}; mem=$((${mem/\.*/} + extraMem))M
+
+        time=`cat $jobRecordDir/stats/$software.$ref.time.stat.noInput | sort -nr | tr '\n' ' ' | cut -f $cutoffRow -d " "`
+        time=$((${time/\.*/} + extraMin))
+        
+#         time=`head -n $((cutoffRow+1)) $jobRecordDir/stats/$software.$ref.time.stat.noInput | tail -n 1`        
+#         time=$((time + extraMin))
+        resAjust="$resAjust#Got estimation based on software.reference: $software.$ref.\n" 
+        resAjust="$resAjust#Give ${extraMem}M extra memory and $extraMin more minutes. \n#So use this to submit the job: $mem  ${time}m"
+        
+    else 
+        resAjust="$resAjust#There are less than 3 job records. Use default mem and time."
+    fi
+
+
 # not depends on other job, and there is input file list
-if [ -z "$deps" ] &&  [[ "$inputs" != "none" ]]; then
+elif [ -z "$deps" ]; then
+    echo Does not depend on other jobs and have inputs.
     inputSize=`{ du --apparent-size -c -L ${inputs//,/ } 2>/dev/null || echo notExist; } | tail -n 1 | cut -f 1`
 
     if [[ "$inputSize" == "notExist" ]]; then 
@@ -469,7 +531,7 @@ if [ -z "$deps" ] &&  [[ "$inputs" != "none" ]]; then
                 
                 cd -
 
-                rm -r $OUT 2>/dev/null
+                
 
                 echo got files in $jobRecordDir/stats:  
                 #ls -lrt $jobRecordDir/stats
@@ -486,70 +548,16 @@ if [ -z "$deps" ] &&  [[ "$inputs" != "none" ]]; then
                     fi 
                 fi        
             fi
+            rm -r $OUT 2>/dev/null
         fi
        
     fi
-# do not have input file list    #todo: we can try to figure out the input from the software parameters here
-elif [[ "$inputs" == "none" ]]; then
-    ref=${ref//\//-}
-    
-    rows=`( wc -l $jobRecordDir/stats/$software.$ref.mem.stat.noInput 2>/dev/null || echo 0 ) | awk '{print $1}'`
-    #echo rows  $rows >&2
-    # empty or more than 60 minutes but less than 4 records
-    if test `find $jobRecordDir/stats/$software.$ref.mem.stat.noInput -mmin +60 2>/dev/null` && [ $rows -lt 3 ] || [ $rows -eq 0 ]; then  
-        mkdir -p $jobRecordDir/stats/
-        #cat /home/*/smartSlurm/stats/myJobRecord.txt > $jobRecordDir/stats/jobRecord.txt 
-        #test `find $jobRecordDir/jobRecord.txt -mmin +20` && echo jobRecord.txt synced within 21 hour. No need to re-sync || cat $HOME/smartSlurm/myJobRecord.txt > $jobRecordDir/jobRecord.txt  
-
-        # todo: could use single file here
-        grep COMPLETED $jobRecordDir/jobRecord.txt 2>/dev/null | awk -F, -v a=$software -v b=$ref '{ if($12 == a && $13 == b) {print $7 }}' > $jobRecordDir/stats/$software.$ref.mem.stat.noInput
-     
-        grep COMPLETED $jobRecordDir/jobRecord.txt 2>/dev/null | awk -F, -v a=$software -v b=$ref '{ if($12 == a && $13 == b) {print $8 }}' > $jobRecordDir/stats/$software.$ref.time.stat.noInput
-        
-        if [ -s $jobRecordDir/stats/$software.$ref.mem.stat.noInput ] && [ -s $jobRecordDir/stats/$software.$ref.time.stat.noInput ]; then 
-            
-            OUT="$(mktemp -d)"
-            paste $jobRecordDir/stats/$software.$ref.time.stat.noInput $jobRecordDir/stats/$software.$ref.mem.stat.noInput | column -s $'\t' -t | sed '$ d' > $jobRecordDir/stats/$software.$ref.timeMem.noInput.txt
-
-            cp $jobRecordDir/stats/$software.$ref.timeMem.noInput.txt $OUT/timeMem.txt
-            cd $OUT
-            # make plot and calculate statistics
-            gnuplot -e 'set term pdf; set output "timeMem.pdf"; set title "Time vs. Memory Usage" font "Helvetica Bold,18"; set xlabel "Time(Min)"; set ylabel "Memory(M)"; f(x)=a*x+b; fit f(x) "timeMem.txt" u 1:2 via a, b; t(a,b)=sprintf("f(x) = %.2fx + %.2f", a, b); plot "timeMem.txt" u 1:2,f(x) t t(a,b); print "Finala=", a; print "Finalb=",b; stats "timeMem.txt" u 1 ' 2>&1 | grep 'Final\| M' | awk 'NF<4{print $1, $2}' |sed 's/:/=/' | sed 's/ //g' > $software.$ref.timeMem.stat.noInput.txt
-
-            cd - 
-            convert $OUT/timeMem.pdf -background White -flatten $jobRecordDir/stats/$software.$ref.stat.noInput.pdf 2>/dev/null
-            pdftoppm $jobRecordDir/stats/$software.$ref.stat.noInput.pdf  -png > $jobRecordDir/stats/$software.$ref.stat.noInput.png 2>/dev/null
-            
-            rows=`{ wc -l $jobRecordDir/stats/$software.$ref.mem.stat.noInput 2>/dev/null || echo 0; } | cut -f 1 -d " "` 
-        
-            rm -r $OUT 2>/dev/null 
-        fi
-    fi
-
-    # at least 3 records
-    if [ $rows -gt 3 ]; then
-        cutoffRow=$(( ($row - 1)  / 10  + 1)) # top 10
-        
-        mem=`cat $jobRecordDir/stats/$software.$ref.mem.stat.noInput | sort -nr | tr '\n' ' ' | cut -f $cutoffRow -d " "`
-        mem=$((${mem/\.*/} + extraMem))M
-#       mem=${txt[$cutoffRow]}; mem=$((${mem/\.*/} + extraMem))M
-
-        time=`cat $jobRecordDir/stats/$software.$ref.time.stat.noInput | sort -nr | tr '\n' ' ' | cut -f $cutoffRow -d " "`
-        time=$((${time/\.*/} + extraMin))
-        
-#         time=`head -n $((cutoffRow+1)) $jobRecordDir/stats/$software.$ref.time.stat.noInput | tail -n 1`        
-#         time=$((time + extraMin))
-        resAjust="$resAjust#Got estimation based on software.reference: $software.$ref.\n" 
-        resAjust="$resAjust#Give ${extraMem}M extra memory and $extraMin more minutes. \n#So use this to submit the job: $mem  ${time}m"
-        
-    else 
-        resAjust="$resAjust#There are less than 3 job records. Use default mem and time."
-    fi
 else
-    resAjust="$resAjust#Use default mem and time. There is no input or input not available yet. Or this job depends on other job."
+    echo Has input, but depends on other jobs
+    resAjust="$resAjust#Use default mem and time. Has input, but this job depends on other job."
 fi
 
-echo
+#echo
 
 [ -z "$time" ] && { echo did not find time limit >&2; exit 1; }
  
@@ -600,7 +608,7 @@ echo
 echo Building new sbatch command ... >&2
 #echo "#!/bin/bash" > $job 
 
-echo -e "#!/bin/bash\n$resAjust\n\ntrap \"{ cleanUp.sh \\\"$logDir\\\" \"$software\" \"${ref//\//-}\" \\\"$flag\\\" \"$inputSize\" \"$core\" \"$memO\" \"$timeO\" \"$mem\" \"$time\" \"$partition\"  \\\"${slurmAcc#*-A }\\\" \"$inputs\" \\\"$0 $@\\\"; }\" EXIT\n" > $job
+echo -e "#!/bin/bash\n$resAjust\n\ntrap \"{ cleanUp.sh \\\"$logDir\\\" \"$software\" \"${ref//\//-}\" \\\"$flag\\\" \"$inputSize\" \"$core\" \"$memO\" \"$timeO\" \"$mem\" \"$(($day * 24 * 60 + $hour * 60 + $min + 1))\" \"$partition\"  \\\"${slurmAcc#*-A }\\\" \"$inputs\"; }\" EXIT\ngetMaxMem.sh &\n" > $job
 
 if [ -z "$slurmScript" ]; then 
     #echo "touch $startFlag" >> $job
@@ -611,6 +619,7 @@ else
     #echo "touch $startFlag" >> $job
     echo "srun -n 1 $slurmAcc bash -e -c \"{ sh $slurmScript $slurmScriptParas; } && touch $succFlag\"" >> $job 
 fi
+#echo "kill -9 \$mypid" >> $job
 #echo "sleep 15 # wait slurm get the job status into its database" >> $job 
 
 #echo "echo Job done. Summary:" >> $job 
