add final summary, barchart

diff --git a/bin/ssbatch b/bin/ssbatch
--- a/bin/ssbatch
+++ b/bin/ssbatch
@@ -37,9 +37,6 @@
 #set -e
 #set -x 
 
-# extraMin=5 # 5min. extra minutes than the estimated time
-# extraMem=5  # 5M. extra memory than the estinated memory
-
 usage() { echo -e "Short Usage: \n${0##*/} [-L logDir (for smartPipline)]  [-S software] [-R reference] [-F uniqueJobFlag (for smartPieline)s] [-I inputList] [-D Dependencies (for smartPipeline)] [sbatch options] [run]\nDetail Detail Usage:\n${0##*/} [-L logDir, optional. Such as: ./], [-S software, optional. Such as: bowtie2-4core. If empty, use script name as software name] [-R reference, optional. Such as: hg19] [-F uniqueJobFlag, optional. Such as 1.bowtie.s1.fa] [-I inputFileOrFolderList, optional. Such as: read1.fq,read2.fq] [ -D dependent jobs] <regular sbatch options, optional. Such as: job.sh or -p short -c 1 -t 2:0:0 --mem 2G --wrap \"my_application para1 para2\"> [run, optional: run will submit job, empty will do a dry run without submitting a job.]"; exit 1; }
 
 [ -z "$1" ] && usage
@@ -270,8 +267,20 @@ if [ -z "$mem" ]; then
     if [ -z "$mem1" ]; then
         mem=$defaultMem
     else
-        [[ "$mem1" == *G ]] && mem=$(( ${mem1%G} * $core ))G || mem=$(( ${mem1%M} * $core ))M
+        [[ "$mem1" == *G ]] && mem=$(( ${mem1%G} * $core * 1024)) || mem=$(( ${mem1%M} * $core ))
     fi
+else 
+    [[ "$mem" == *G ]] && mem=$(( ${mem%G} * 1024 )) || mem=${mem%M}   
+fi
+
+if [ -z "$time" ]; then 
+    min=$defaultTime
+else
+    [[ "$time" == *-* ]] && { day=${time%-*}; tem=${time#*-}; hour=${tem%%:*}; min=${tem#*:}; min=${min%%:*}; sec=${tem#$hour:$min}; sec=${sec#:}; } || { [[ "$time" =~ ^[0-9]+$ ]] && min=$time || { sec=${time##*:}; min=${time%:*}; min=${min##*:}; hour=${time%$min:$sec}; hour=${hour%:}; day=0;} }
+
+    [ -z "$day" ] && day=0; [ -z "$hour" ] && hour=0; [ -z "$min" ] && min=0;[ -z "$sec" ] && sec=0
+
+    min=$(($day * 24 * 60 + $hour * 60  + $min))
 fi
 
 if [[ $deps == null ]]; then
@@ -291,7 +300,7 @@ else
     [ ! -z "$tmp" ] && deps="--dependency=afterok$tmp"
 fi
 
-resAjust="#Original mem $mem, Original time: $time\n"
+resAjust="#Original mem $mem M, Original time: $min mins\n"
 
 # check job done before or not
 if [[ ! -z "$logDir" && "$testRun" == "run" ]]; then 
@@ -372,10 +381,10 @@ if [[ ! -z "$logDir" && "$testRun" == "run" ]]; then
     rm $flagDir/$flag.* 2>/dev/null || : # in case user has set -e and file not exist,  we will not exit
 fi
 
-[ -z "$time" ] && time=$defaultTime
+[ -f $jobRecordDir/stats/$software.$ref.extraMem ] && extraMem=`cat $jobRecordDir/stats/$software.$ref.extraMem`
 
 # original mem and time 
-memO=$mem; timeO=$time
+memO=$mem; minO=$min
 inputSize=0
 
 echo 
@@ -397,9 +406,9 @@ if [[ "$inputs" == "none" ]]; then
         #test `find $jobRecordDir/jobRecord.txt -mmin +20` && echo jobRecord.txt synced within 21 hour. No need to re-sync || cat $HOME/smartSlurm/myJobRecord.txt > $jobRecordDir/jobRecord.txt  
 
         # todo: could use single file here
-        grep COMPLETED $jobRecordDir/jobRecord.txt 2>/dev/null | awk -F, -v a=$software -v b=$ref '{ if($12 == a && $13 == b) {print $7 }}' > $jobRecordDir/stats/$software.$ref.mem.stat.noInput
+        grep COMPLETED $jobRecordDir/jobRecord.txt 2>/dev/null | awk -F, -v a=$software -v b=$ref '{ if($12 == a && $13 == b) {print $7 }}' | uniq > $jobRecordDir/stats/$software.$ref.mem.stat.noInput
      
-        grep COMPLETED $jobRecordDir/jobRecord.txt 2>/dev/null | awk -F, -v a=$software -v b=$ref '{ if($12 == a && $13 == b) {print $8 }}' > $jobRecordDir/stats/$software.$ref.time.stat.noInput
+        grep COMPLETED $jobRecordDir/jobRecord.txt 2>/dev/null | awk -F, -v a=$software -v b=$ref '{ if($12 == a && $13 == b) {print $8 }}' | uniq > $jobRecordDir/stats/$software.$ref.time.stat.noInput
         
         if [ -s $jobRecordDir/stats/$software.$ref.mem.stat.noInput ] && [ -s $jobRecordDir/stats/$software.$ref.time.stat.noInput ]; then 
             
@@ -426,16 +435,14 @@ if [[ "$inputs" == "none" ]]; then
         cutoffRow=$(( ($row - 1)  / 10  + 1)) # top 10
         
         mem=`cat $jobRecordDir/stats/$software.$ref.mem.stat.noInput | sort -nr | tr '\n' ' ' | cut -f $cutoffRow -d " "`
-        mem=$((${mem/\.*/} + extraMem))M
+        mem=$((${mem/\.*/} + extraMem))
 #       mem=${txt[$cutoffRow]}; mem=$((${mem/\.*/} + extraMem))M
 
-        time=`cat $jobRecordDir/stats/$software.$ref.time.stat.noInput | sort -nr | tr '\n' ' ' | cut -f $cutoffRow -d " "`
-        time=$((${time/\.*/} + extraMin))
+        min=`cat $jobRecordDir/stats/$software.$ref.time.stat.noInput | sort -nr | tr '\n' ' ' | cut -f $cutoffRow -d " "`
+        min=$((${min/\.*/} + extraMin))
         
-#         time=`head -n $((cutoffRow+1)) $jobRecordDir/stats/$software.$ref.time.stat.noInput | tail -n 1`        
-#         time=$((time + extraMin))
         resAjust="$resAjust#Got estimation based on software.reference: $software.$ref.\n" 
-        resAjust="$resAjust#Give ${extraMem}M extra memory and $extraMin more minutes. \n#So use this to submit the job: $mem  ${time}m"
+        resAjust="$resAjust#Give ${extraMem}M extra memory and $extraMin more minutes. \n#So use this to submit the job: $mem M  ${min} min"
         
     else 
         resAjust="$resAjust#There are less than 3 job records. Use default mem and time."
@@ -464,8 +471,8 @@ elif [ -z "$deps" ]; then
                 resAjust="$resAjust#Input size is too big for the curve to estimate! Use default mem and runtime to submit job.\n"
                 # not deleting mem.stat, so other jobs will not re-build it within 60 minutes
             elif [ ! -z "$output" ]; then
-                mem=$((${output% *}+extraMem))M; time=$((${output#* }+extraMin));     
-                resAjust="$resAjust#Give ${extraMem}M extra memory and $extraMin more minutes. \n#So use this to submit the job: $mem  ${time}m"
+                mem=$((${output% *}+extraMem)); min=$((${output#* }+extraMin));     
+                resAjust="$resAjust#Give ${extraMem}M extra memory and $extraMin more minutes. \n#So use this to submit the job: $mem M  ${min} mins"
             fi 
         
         fi
@@ -543,8 +550,8 @@ elif [ -z "$deps" ]; then
                         resAjust="$resAjust#Input size is too big for the curve to estimate! Use default mem and runtime to submit job.\n"
                         # not deleting mem.stat, so other jobs will not re-build it within 60 minutes
                     elif [ ! -z "$output" ]; then
-                        mem=$((${output% *}+extraMem))M; time=$((${output#* }+extraMin));     
-                        resAjust="$resAjust#Give ${extraMem}M extra memory and $extraMin more minutes. \n#So use this to submit the job: $mem  ${time}m"
+                        mem=$((${output% *}+extraMem)); min=$((${output#* }+extraMin));     
+                        resAjust="$resAjust#Give ${extraMem}M extra memory and $extraMin more minutes. \n#So use this to submit the job: $mem M ${min} mins"
                     fi
                     #echo got estimation $output  
                 fi        
@@ -560,35 +567,32 @@ fi
 
 #echo
 
-[ -z "$time" ] && { echo did not find time limit >&2; exit 1; }
+[ -z "$min" ] && { echo did not find time limit >&2; exit 1; }
  
 [ -z "$mem" ] && { echo did not find mem limit >&2; exit 1; } 
 
 [ -z "$core" ] && { [ ! -z "$task" ] && core="$task" || core=1; } 
 
-[[ "$time" == *-* ]] && { day=${time%-*}; tem=${time#*-}; hour=${tem%%:*}; min=${tem#*:}; min=${min%%:*}; sec=${tem#$hour:$min}; sec=${sec#:}; } || { [[ "$time" =~ ^[0-9]+$ ]] && min=$time || { sec=${time##*:}; min=${time%:*}; min=${min##*:}; hour=${time%$min:$sec}; hour=${hour%:}; day=0;} }
+#time=$min
 
-[ -z "$day" ] && day=0; [ -z "$hour" ] && hour=0; [ -z "$min" ] && min=0;[ -z "$sec" ] && sec=0
+#[[ "$time" == *-* ]] && { day=${time%-*}; tem=${time#*-}; hour=${tem%%:*}; min=${tem#*:}; min=${min%%:*}; sec=${tem#$hour:$min}; sec=${sec#:}; } || { [[ "$time" =~ ^[0-9]+$ ]] && min=$time || { sec=${time##*:}; min=${time%:*}; min=${min##*:}; hour=${time%$min:$sec}; hour=${hour%:}; day=0;} }
+
+#[ -z "$day" ] && day=0; [ -z "$hour" ] && hour=0; [ -z "$min" ] && min=0;[ -z "$sec" ] && sec=0
 
 # resAjust="$resAjust#day $day,  hour $hour,  min $min,  sec $sec"
 
-# how many hours for sbatch command
-hours=$(($day * 24 + $hour + ($min + 59 + ($sec + 59) / 60 ) / 60))
-
 #echo looking partition for hour: $hours 
 
-adjustPartition $hours $partition
-
-time=$day-$hour:$min:$sec
+adjustPartition $(( ( $min + 59 ) / 60 )) $partition
 
 # 10 minutes less than the time in sbatch command
-#seconds=$(($day * 24 * 60 * 60 + $hour * 60 * 60  + $min * 60 + $sec - 600))
+seconds=$(( $min * 60 ))
 
 #[ $seconds -le 60 ] && time=11:0 && seconds=60
 
 #echo srun seconds: $seconds
 
-#timeN=`eval "echo $(date -ud "@$seconds" +'$((%s/3600/24))-%H:%M:%S')"`
+time=`eval "echo $(date -ud "@$seconds" +'$((%s/3600/24))-%H:%M:%S')"`
 
 #echo New time for srun: $timeN
 
@@ -607,33 +611,33 @@ time=$day-$hour:$min:$sec
 
 echo 
 echo Building new sbatch command ... >&2
-#echo "#!/bin/bash" > $job 
+#echo "#!/bin/bash" > $job   
 
-echo -e "#!/bin/bash\n$resAjust\n\ntrap \"{ cleanUp.sh \\\"$logDir\\\" \"$software\" \"${ref//\//-}\" \\\"$flag\\\" \"$inputSize\" \"$core\" \"$memO\" \"$timeO\" \"$mem\" \"$(($day * 24 * 60 + $hour * 60 + $min + 1))\" \"$partition\"  \\\"${slurmAcc#*-A }\\\" \"$inputs\"; }\" EXIT\ngetMaxMem.sh &\n" > $job
+echo -e "#!/bin/bash\n$resAjust\n\ntrap \"{ cleanUp.sh \\\"$logDir\\\" \"$software\" \"${ref//\//-}\" \\\"$flag\\\" \"$inputSize\" \"$core\" \"$memO\" \"$minO\" \"$mem\" \"$min\" \"$partition\"  \\\"${slurmAcc#*-A }\\\" \"$inputs\"; }\" EXIT\ngetMaxMem.sh &\n" > $job
 
-[[ "$mem" == *G ]] && totalM=$(( 1024 * ${mem%G})) || totalM=${mem%M}
+# [[ "$mem" == *G ]] && totalM=$(( 1024 * ${mem%G})) || totalM=${mem%M}
 
-[ $totalM -lt 20 ] && totalM=20
+# [ $totalM -lt 20 ] && totalM=20
 
-#echo "set -x" >> $job
-echo "if [ ! -f log/$flag.adjust ]; then" >> $job
-echo "   totalM=$totalM" >> $job
-echo "else " >> $job
-echo "   totalM=\`cat log/$flag.adjust\`" >> $job
-## todo: this might work if cluster is bussy, may need sleep more or get the data from a text file
-#echo "   sleep 10; sacct=\`sacct --format=JobID,Submit,Start,End,MaxRSS,State,NodeList%30,Partition,ReqTRES%30,TotalCPU,Elapsed%14,Timelimit%14 --units=M -j \$SLURM_JOBID\` " #>> $job
-#echo "   totalM=\${sacct#*,mem=}; totalM=\${totalM%%M,n*}" >> $job
-echo "fi" >> $job 
-echo "srunM=\$((\$totalM - 15))M" >> $job
+# #echo "set -x" >> $job
+# echo "if [ ! -f log/$flag.adjust ]; then" >> $job
+# echo "   totalM=$totalM" >> $job
+# echo "else " >> $job
+# echo "   totalM=\`cat log/$flag.adjust\`" >> $job
+# ## todo: this might work if cluster is bussy, may need sleep more or get the data from a text file
+# #echo "   sleep 10; sacct=\`sacct --format=JobID,Submit,Start,End,MaxRSS,State,NodeList%30,Partition,ReqTRES%30,TotalCPU,Elapsed%14,Timelimit%14 --units=M -j \$SLURM_JOBID\` " #>> $job
+# #echo "   totalM=\${sacct#*,mem=}; totalM=\${totalM%%M,n*}" >> $job
+# echo "fi" >> $job 
+# #echo "srunM=\$((\$totalM - 15))M" >> $job
  
 if [ -z "$slurmScript" ]; then 
     #echo "touch $startFlag" >> $job
     wrapCMD=`echo $wrapCMD | xargs echo -n`; wrapCMD=${wrapCMD%;} # remove ending space and ; from command
-    echo "srun --mem \$srunM -n 1 $slurmAcc bash -e -c \"{ $wrapCMD; } && touch $succFlag\"" >> $job 
+    echo "srun -n 1 $slurmAcc bash -e -c \"{ $wrapCMD; } && touch $succFlag\"" >> $job 
 else 
     grep "^#SBATCH" $slurmScript >> $job || : >> $job
     #echo "touch $startFlag" >> $job
-    echo "srun -mem \$srunM -n 1 $slurmAcc bash -e -c \"{ sh $slurmScript $slurmScriptParas; } && touch $succFlag\"" >> $job 
+    echo "srun -n 1 $slurmAcc bash -e -c \"{ sh $slurmScript $slurmScriptParas; } && touch $succFlag\"" >> $job 
 fi
 #echo "kill -9 \$mypid" >> $job
 #echo "sleep 15 # wait slurm get the job status into its database" >> $job 
@@ -662,9 +666,9 @@ fi
 #mem=2000M
 
 if [ -z "$logDir" ]; then
-    cmd="/usr/bin/sbatch --mail-type=FAIL --requeue --parsable -p $partition --mem ${totalM}M -t $time --open-mode=append $slurmAcc"
+    cmd="/usr/bin/sbatch --mail-type=FAIL --requeue --parsable -p $partition --mem $mem -t $time --open-mode=append $slurmAcc"
 else
-    cmd="/usr/bin/sbatch --mail-type=FAIL --requeue --parsable -p $partition --mem ${totalM}M -t $time --open-mode=append -o $outFlag -e $outFlag -J $flag $deps $slurmAcc"
+    cmd="/usr/bin/sbatch --mail-type=FAIL --requeue --parsable -p $partition --mem $mem -t $time --open-mode=append -o $outFlag -e $outFlag -J $flag $deps $slurmAcc"
     #rm $startFile $failFile $flag.failed $flag.killed # 2>/dev/null  || : 
 fi
 if [ -z "$slurmScript" ]; then 
@@ -719,5 +723,3 @@ echo New slurmScirpt is ready. The content is: >&2
 cat $job >&2
 
 echo Submitted batch job $jobID
-
-
