add single Job plots

diff --git a/bin/ssbatch b/bin/ssbatch
--- a/bin/ssbatch
+++ b/bin/ssbatch
@@ -262,11 +262,6 @@ fi
 
 [ -z "$core" ] && { [ ! -z "$task" ] && core="$task" || core=1; }
 
-#[ -z "$program" ] && [ ! -z "$P" ] && program="$P"
-#[ -z "$ref" ] && [ ! -z "$R" ] && ref="$R"
-#[ -z "$input" ] && [ ! -z "$I" ] && inputs="$I"
-#[ -z "$deps" ] && [ ! -z "$d" ] && deps="$d"
-#[[ "$program" == *Checkpoint ]] || program=$program$C
 [ -z "$out" ] || out=`realpath $out`
 [ -z "$err" ] || err=`realpath $err`
 #todo: err is ignored. will work on it later
@@ -313,8 +308,6 @@ killFlag=$smartSlurmLogDir/$flag.user.killed
 outFlag=$smartSlurmLogDir/$flag.out
 errFlag=$smartSlurmLogDir/$flag.err
 
-#deps=${deps#.}
-
 [ -z "$ref" ] && ref=none
 [ -z "$inputs" ] && inputs=none
 if [ -z "$deps" ]; then 
@@ -346,23 +339,6 @@ else
 fi
 
 resAjust="#Depend on: $depsID\n"
-
-# if [[ $deps == "null" ]]; then
-#     deps=""
-#     resAjust="#Depend on no job\n"
-
-# elif [[ $deps == ${deps/\./} ]]; then
-#     resAjust="#Depend on single job\n"
-#     deps="--dependency=afterok:${deps/\./}"
-# else
-#     resAjust="#Depend on multiple jobs\n"
-#     tmp=""
-#     for t in ${deps//\./ }; do
-#         #echoerr working on $t  test
-#         tmp="$tmp:$t"
-#     done
-#     [ ! -z "$tmp" ] && deps="--dependency=afterok$tmp"
-# fi
 
 resAjust="#Original mem $mem M, Original time: $min mins\n"
 
@@ -450,21 +426,8 @@ if [[ "$testRun" == "run" ]]; then
                 fi
             else
                 if [ -z "$deps" ]; then
-                    depsR="" #dependency=\"\""
-                    #resAjust="#Depend on
-
-                #elif [[ $depsID == ${depsID/:/} ]]; then
-                #    #resAjust="#Depend on single job\n"
-                #    depsR="dependency=afterok:${depsID/:/}"
+                    depsR="" #dependency=\"\""      
                 else
-                    #resAjust="#Depend on multiple jobs\n"
-                    # tmp=""
-                    # for t in ${depsID//:/ }; do
-                    #     #echoerr working on $t  test
-                    #     tmp="$tmp:$t"
-                    # done
-                    # [ ! -z "$tmp" ] && depsR="dependency=afterok$tmp"
-
                     epsR="dependency=$deps"
                 fi
 
@@ -485,8 +448,6 @@ if [[ "$testRun" == "run" ]]; then
     #ls $flagDir/$flag.* 1>&2
     rm -r $smartSlurmLogDir/$flag $smartSlurmLogDir/$flag.* 2>/dev/null || : # in case user has set -e and file not exist,  we will not exit
 fi
-
-#[ -f $smartSlurmJobRecordDir/stats/extraMem.$program.$ref ] && maxExtra=`sort -n $smartSlurmJobRecordDir/stats/extraMem.$program.$ref | tail -n1 | cut -d' ' -f1` && oomCount=`wc -l $smartSlurmJobRecordDir/stats/extraMem.$program.$ref | cut -d' ' -f1` && extraMem=$(( $maxExtra * $oomCount ))
 
 [ -f $smartSlurmJobRecordDir/stats/extraMem.$program.$ref ] && maxExtra=`sort -n $smartSlurmJobRecordDir/stats/extraMem.$program.$ref | tail -n1 | cut -d' ' -f1` && extraMem=$(( $maxExtra * 2 )) || extraMem=$(($defaultExtraMem * 2))
 
@@ -539,13 +500,8 @@ else
                 # make plot and calculate statistics
                 gnuplot -e 'set key outside; set key reverse; set key invert; set term png; set output "'"$smartSlurmJobRecordDir/stats/$program.$ref.stat.noInput.png"'"; set title "Time vs. Memory Usage"; set xlabel "Time(Min)"; set ylabel "Memory(M)"; f(x)=a*x+b; fit f(x) "'"$smartSlurmJobRecordDir/stats/$program.$ref.timeMem.noInput"'" u 1:2 via a, b; t(a,b)=sprintf("f(x) = %.2fx + %.2f", a, b); plot "'"$smartSlurmJobRecordDir/stats/$program.$ref.timeMem.noInput"'" u 1:2,f(x) t t(a,b); print "Finala=", a; print "Finalb=",b; stats "'"$smartSlurmJobRecordDir/stats/$program.$ref.timeMem.noInput"'" u 1 ' 2>&1 | grep 'Final\| M' | awk 'NF<5{print $1, $2}' | sed 's/:/=/' | sed 's/ //g' > $smartSlurmJobRecordDir/stats/$program.$ref.timeMem.stat.noInput
 
-                # cd -
-                # convert $OUT/timeMem.pdf -background White -flatten $smartSlurmJobRecordDir/stats/$program.$ref.stat.noInput.pdf 2>/dev/null
-                # pdftoppm $smartSlurmJobRecordDir/stats/$program.$ref.stat.noInput.pdf  -png > $smartSlurmJobRecordDir/stats/$program.$ref.stat.noInput.png 2>/dev/null
-
                 rows=`{ wc -l $smartSlurmJobRecordDir/stats/$program.$ref.mem.noInput 2>/dev/null || echo 0; } | cut -f 1 -d " "`
 
-                #rm -r $OUT 2>/dev/null
             fi
         fi
 
@@ -610,11 +566,6 @@ else
             if [[ "$output" == "outOfRange" ]] && test `find $smartSlurmJobRecordDir/stats/$program.${ref//\//-}.mem.stat -mmin +20` || [ ! -f $smartSlurmJobRecordDir/stats/$program.${ref//\//-}.mem.stat ]; then
                 resAjust="$resAjust#Do not have a formula, or it is old and out of range. Let us build one...\n"
 
-                #[ test `find $smartSlurmJobRecordDir/jobRecord.txt -mmin -20` ] && echoerr jobRecord.txt synced within 20 hour. No need to re-sync || cat $HOME/smartSlurm/myJobRecord.txt > $smartSlurmJobRecordDir/jobRecord.txt
-
-                #jobStatistics.sh $program ${ref//\//-} 4 1>&2
-
-
                 #filter by program and reference
                 # todo: maybe able to replace / in ref at begaining of the script?
                 ref=${ref//\//-}
@@ -633,13 +584,6 @@ else
                     resAjust="$resAjust#There are less than 3 records. No way to fit a curve.\n"
 
                 else
-
-
-
-                    # make plot and calculate statistics
-                    # gnuplot -e 'set term pdf; set output "mem.pdf"; set title "Input Size vs. Memory Usage" font "Helvetica Bold,18"; set xlabel "Input Size(K)"; set ylabel "Memory Usage(M)"; f(x)=a*x+b; fit f(x) "mem.txt" u 1:2 via a, b; t(a,b)=sprintf("f(x) = %.2fx + %.2f", a, b); plot "mem.txt" u 1:2,f(x) t t(a,b); print "Finala=", a; print "Finalb=",b; stats "mem.txt" u 1 ' 2>&1 | grep 'Final\| M' | awk 'NF<4{print $1, $2}' |sed 's/:/=/' | sed 's/ //g' > mem.stat.txt; echo STDFIT=`cat fit.log | grep FIT_STDFIT | tail -n 1 | awk '{print $8}'` >> mem.stat.txt
-                    # echo RSquare="$(gnuplot -e 'stats "mem.txt" using 1:2;' 2>&1| grep Correlation | cut -d' ' -f7 | awk '{print $1 * $1 }')" >> mem.stat.txt
-
                     gnuplot -e 'set key outside; set key reverse; set key invert; set term png; set output "'"$smartSlurmJobRecordDir/stats/$program.$ref.mem.png"'"; set title "Input Size vs. Memory Usage"; set xlabel "Input Size(K)"; set ylabel "Memory Usage(M)"; f(x)=a*x+b; fit f(x) "'"$smartSlurmJobRecordDir/stats/$program.$ref.mem"'" u 1:2 via a, b; t(a,b)=sprintf("f(x) = %.2fx + %.2f", a, b); plot "'"$smartSlurmJobRecordDir/stats/$program.$ref.mem"'" u 1:2,f(x) t t(a,b); print "Finala=", a; print "Finalb=",b; stats "'"$smartSlurmJobRecordDir/stats/$program.$ref.mem"'" u 1 ' 2>&1 | grep 'Final\| M' | awk 'NF<5{print $1, $2}' |sed 's/:/=/' | sed 's/ //g' > $smartSlurmJobRecordDir/stats/$program.$ref.mem.stat ; echo STDFIT=`cat fit.log | grep FIT_STDFIT | tail -n 1 | awk '{print $8}'` >> $smartSlurmJobRecordDir/stats/$program.$ref.mem.stat
 
                     echo RSquare="$(gnuplot -e 'stats "'"$smartSlurmJobRecordDir/stats/$program.$ref.mem"'" using 1:2;' 2>&1| grep Correlation | cut -d' ' -f7 | awk '{print $1 * $1 }')" >> $smartSlurmJobRecordDir/stats/$program.$ref.mem.stat
@@ -654,37 +598,10 @@ else
 
                     sed -i 's/\x0//g' $smartSlurmJobRecordDir/stats/$program.$ref.time.stat
 
-
-
-                    # make plot and calculate statistics
-                    # gnuplot -e 'set term pdf; set output "time.pdf"; set title "Input Size vs. Time Usage" font "Helvetica Bold,18"; set xlabel "Input Size(K)"; set ylabel "Time(Min)"; f(x)=a*x+b; fit f(x) "time.txt" u 1:2 via a, b; t(a,b)=sprintf("f(x) = %.2fx + %.2f", a, b); plot "time.txt" u 1:2,f(x) t t(a,b); print "Finala=", a; print "Finalb=",b; stats "time.txt" u 1 ' 2>&1 | grep 'Final\| M' | awk 'NF<4{print $1, $2}' |sed 's/:/=/' | sed 's/ //g' > time.stat.txt; echo STDFIT=`cat fit.log | grep FIT_STDFIT | tail -n 1 | awk '{print $8}'` >> time.stat.txt
-                    # echo RSquare="$(gnuplot -e 'stats "time.txt" using -1:2;' 2>&1| grep Correlation | cut -d' ' -f7 | awk '{print $1 * $1 }')" >> time.stat.txt
-
-                    echoerr There are more than 3 $program $ref jobs already run for this program, statics is ready for current job:
-                    # echoerr Memeory statisics:
-                    # echoerr "inputsize mem(M)"
-                    # cat $smartSlurmJobRecordDir/stats/$program.$ref.mem.stat
-                    # echoerr
-                    # echoerr Time statistics:
-                    # echoerr "inputsize time(minute)"
-                    # cat $smartSlurmJobRecordDir/stats/$program.$ref.time.stat
-
-                    # mv $OUT/mem.txt $smartSlurmJobRecordDir/stats/$program.$ref.mem
-                    # mv $OUT/time.txt $smartSlurmJobRecordDir/stats/$program.$ref.time
-
-                    # convert $OUT/mem.pdf -background White -flatten $smartSlurmJobRecordDir/stats/$program.$ref.mem.pdf
-                    # convert $OUT/time.pdf -background White -flatten $smartSlurmJobRecordDir/stats/$program.$ref.time.pdf
-                    # pdftoppm $smartSlurmJobRecordDir/stats/$program.$ref.mem.pdf  -png > $smartSlurmJobRecordDir/stats/$program.$ref.mem.png
-                    # pdftoppm $smartSlurmJobRecordDir/stats/$program.$ref.time.pdf  -png > $smartSlurmJobRecordDir/stats/$program.$ref.time.png
-
                     echoerr
                     echoerr You can see the plot using commands:
                     echoerr display $smartSlurmJobRecordDir/stats/$program.$ref.mem.png
                     echoerr display $smartSlurmJobRecordDir/stats/$program.$ref.time.png
-
-                    # cd -
-
-
 
                     #echoerr got files in $smartSlurmJobRecordDir/stats:
                     #ls -lrt $smartSlurmJobRecordDir/stats
@@ -723,25 +640,9 @@ else
     
 fi
 
-#echoerr
-
-# for OOM memtesting
-#mem=4000
-
 [ -z "$min" ] && { echo did not find time limit; exit 1; }
 
 [ -z "$mem" ] && { echo did not find mem limit; exit 1; }
-
-
-#time=$min
-
-#[[ "$time" == *-* ]] && { day=${time%-*}; tem=${time#*-}; hour=${tem%%:*}; min=${tem#*:}; min=${min%%:*}; sec=${tem#$hour:$min}; sec=${sec#:}; } || { [[ "$time" =~ ^[0-9]+$ ]] && min=$time || { sec=${time##*:}; min=${time%:*}; min=${min##*:}; hour=${time%$min:$sec}; hour=${hour%:}; day=0;} }
-
-#[ -z "$day" ] && day=0; [ -z "$hour" ] && hour=0; [ -z "$min" ] && min=0;[ -z "$sec" ] && sec=0
-
-# resAjust="$resAjust#day $day,  hour $hour,  min $min,  sec $sec"
-
-#echoerr looking partition for hour: $hours ##
 
 [ "$mem" -lt 100 ] && mem=100 && resAjust="$resAjust\n#Mem is reset to 100M. "
 
@@ -762,20 +663,6 @@ seconds=$(( $min * 60 ))
 
 time=`eval "echo $(date -ud "@$seconds" +'$((%s/3600/24))-%H:%M:%S')"`
 
-#echoerr New time for srun: $timeN
-
-#echoerr
-
-# mem for srun is 10M less than sbatch command
-#[[ "$mem" == *G ]] && memN=$(( 1024 * ${mem%G} -10 ))M || memN=$(( ${mem%M} -10 ))M
-
-#[ ${memN%M} -le 1 ] && { echoerr Error: --mem for sbatch command should bigger than 11M; usage; }
-#[ ${memN%M} -le 1 ] && mem=20M && memN=10M
-
-#echoerr Mew mem for srun: $memN
-
-#[ -z "$out" ] && out="slurm-\$SLURM_JOBID.out"
-#[ -z "$err" ] && err="slurm-\$SLURM_JOBID.err"
 if [ -f .command.sh ] && [ -f .command.run ]; then 
     cp .command.run .command.run.back 
     sed -i "s/exit \$exit_status/cleanUp.sh $flag $program \\\"${ref//\//-}\\\" $inputSize $core $memO $minO $mem $min $partition  \\\"${slurmAcc#*-A }\\\" \\\"${inputs##*/}\\\" $extraMem $defaultExtraTime\n    exit \$exit_status/" .command.run >> ../../../.nextflow.log
@@ -789,32 +676,7 @@ else
 
     echoerr
     echoerr Building new sbatch command ...
-    #echo "#!/bin/bash" > $job
-
-    #echo -e "#!/bin/bash\ndate\n\ntrap \"{ cleanUp.sh $flag $program ${ref//\//-} $inputSize $core $memO $minO $mem $min $partition  \\\"${slurmAcc#*-A }\\\" \\\"$inputs\\\" $extraMem $defaultExtraTime; }\" EXIT\nmemCpuMonitor.sh $flag $mem $min $memO $core &\n" > $job
-
-    # echo -e "#!/bin/bash\ndate\n\ntrap \"{ cleanUp.sh $flag $program ${ref//\//-} $inputSize $core $memO $minO $mem $min $partition  \\\"${slurmAcc#*-A }\\\" \\\"$inputs\\\" $extraMem $defaultExtraTime; }\" EXIT\nmemCpuMonitor.sh $flag $program ${ref//\//-} $inputSize $core $memO $minO $mem $min $partition \\\"${slurmAcc#*-A }\\\" \\\"$inputs\\\" $extraMem $defaultExtraTime &\n" > $job
-
-
-    # [[ "$mem" == *G ]] && totalM=$(( 1024 * ${mem%G})) || totalM=${mem%M}
-
-    # #echo "set -x" >> $job
-    # echo "if [ ! -f $smartSlurmLogDir/$flag.adjust ]; then" >> $job
-    # echo "   totalM=$totalM" >> $job
-    # echo "else " >> $job
-    # echo "   totalM=\`cat $smartSlurmLogDir/$flag.adjust\`" >> $job
-    # ## this might work if cluster is bussy, may need sleep more or get the data from a text file
-    # #echo "   sleep 10; sacct=\`sacct --format=JobID,Submit,Start,End,MaxRSS,State,NodeList%30,Partition,ReqTRES%30,TotalCPU,Elapsed%14,Timelimit%14 --units=M -j \$SLURM_JOBID\` " #>> $job
-    # #echo "   totalM=\${sacct#*,mem=}; totalM=\${totalM%%M,n*}" >> $job
-    # echo "fi" >> $job
-
-    # when submit jobs from interactive job, need this. Otherwise get error:
-    # echo -e "unset SLURM_MEM_PER_CPU SLURM_MEM_PER_GPU SLURM_MEM_PER_NODE SLURM_CPU_BIND" >> $job
-
-
-    #echo -e "unset SLURM_MEM_PER_CPU SLURM_MEM_PER_GPU SLURM_MEM_PER_NODE SLURM_CPU_BIND" >> $job
-
-
+ 
     if [ -z "$slurmScript" ]; then
         echo -e "#!/bin/bash\ndate\n\ntrap \"{ cleanUp.sh $flag $program ${ref//\//-} $inputSize $core $memO $minO $mem $min $partition  \\\"${slurmAcc#*-A }\\\" \\\"$inputs\\\" $extraMem $defaultExtraTime; }\" EXIT\nmemCpuMonitor.sh $flag $mem $min $memO $core &\n" > $job
         echo -e "unset SLURM_CPU_BIND" >> $job
@@ -863,7 +725,7 @@ else
             
             if [ ! -z "$runningSingleJob" ]; then
 
-                echo "srun -n 1 $slurmAcc sh -e -o pipefail -c '$wrapCMD; ' && summarizeRun.sh $flag && touch $succFlag " >> $job
+                echo "srun -n 1 $slurmAcc sh -e -o pipefail -c '$wrapCMD; ' && touch $succFlag " >> $job
             else 
 
                 # !!! runAsPipeline jobs will land here !!!
@@ -895,20 +757,6 @@ else
         fi
     fi
     #echo "kill -9 \$mypid" >> $job
-    #echo "sleep 15 # wait slurm get the job status into its database" >> $job
-
-    #echo "echo Job done. Summary:" >> $job
-
-    # echo "sacct --format=JobID,Submit,Start,End,MaxRSS,State,NodeList%30,Partition,ReqTRES%30,TotalCPU,Elapsed%14,Timelimit%14 --units=M -j \$SLURM_JOBID" >> $job
-    # #echo SLURM_JOBID=\$SLURM_JOBID >> $job
-
-    # echo "emailAndRecord.sh \"$program\" \"${ref//\//-}\" \"$flag\" \"$inputSize\" \"$core\" \"$memO\" \"$timeO\" \"$mem\" \"$time\"" >> $job #  >/dev/null" >> $job
-
-    # echo "adjustDownStreamJobs.sh $smartSlurmLogDir/" >> $job
-
-    # echo "[ -f $succFlag ] ||  { touch $failFlag; exit 1; }" >> $job
-
-    #[ -z "$dir" ] && dir="./" || mkdir -p $dir
 
     ## todo: need fix this when path not starting with /
     [ -z "$out" ] || ( [[ "$out" == /* ]] && mkdir -p $(dirname $out) || mkdir -p $dir/$(dirname $out) )
@@ -918,22 +766,12 @@ else
     # [ -f $errFlag ] && [ ! -z "$err" ] && [[ ! $errFlag == "$err" ]] && echo ln -s $errFlag $err >> $job
 
 
-    #if [ -z "$smartSlurmLogDir/" ]; then
-    #    cmd="/usr/bin/sbatch --mail-type=FAIL --requeue --parsable -p $partition --mem $mem -t $time --open-mode=append $slurmAcc"
-    #else
+ 
     [ -z "$err" ] && errFlag=$outFlag
-    #[ -z "$deps" ] || deps="-H $deps" # if depends on other jobs, hold the job
-    
-        # if [ -z "$deps" ]; then #errFlag=$smartSlurmLogDir/$flag.err
-        #     cmd="/usr/bin/sbatch --mail-type=FAIL --requeue --parsable -p $partition -c $core --mem $mem -t $time --open-mode=append -o $outFlag -e $outFlag -J $name $slurmAcc"
-        #     echo -ne "\n#Command used to submit the job: /usr/bin/sbatch --mail-type=FAIL --requeue --parsable -p \$myPartition -c $core --mem \$myMem -t \$myTime --open-mode=append -o $outFlag -e $outFlag -J $name $deps $slurmAcc" >> $job
-        # else
-            cmd="/usr/bin/sbatch --mail-type=FAIL --requeue --parsable -p $partition -c $core --mem $mem -t $time --open-mode=append -o $outFlag -e $errFlag -J $name $deps $chdir $onhold $slurmAcc"
-            echo -ne "\n#Command used to submit the job: /usr/bin/sbatch --mail-type=FAIL --requeue --parsable -p \$myPartition -c $core --mem \$myMem -t \$myTime --open-mode=append -o $outFlag -e $errFlag -J $name $deps $chdir $slurmAcc" >> $job
-        #fi
 
-        #rm $startFile $failFile $flag.failed $flag.killed # 2>/dev/null  || :
-    #fi
+    cmd="/usr/bin/sbatch --mail-type=FAIL --requeue --parsable -p $partition -c $core --mem $mem -t $time --open-mode=append -o $outFlag -e $errFlag -J $name $deps $chdir $onhold $slurmAcc"
+    echo -ne "\n#Command used to submit the job: /usr/bin/sbatch --mail-type=FAIL --requeue --parsable -p \$myPartition -c $core --mem \$myMem -t \$myTime --open-mode=append -o $outFlag -e $errFlag -J $name $deps $chdir $slurmAcc" >> $job
+
     if [ -z "$slurmScript" ]; then
         cmd="$cmd $additionalPara $job"
         echo -e " $additionalPara $job" >> $job
@@ -941,32 +779,19 @@ else
         cmd="$cmd $additionalPara $job $slurmScriptParas"
         echo -e " $additionalPara $job $slurmScriptParas" >> $job
     fi
-
-
-
-    #echo -e "\n#Command used to submit the job: $cmd" >> $job
-
-    #echoerr $resAjust
 fi 
 
 echoerr New sbatch command to submit job:
 echoerr $cmd
 if [[ "$testRun" == "run" ]]; then
     echoerr Start submtting job...
-    #output=`$cmd`
-    #echoerr $output
-    #jobID=`$cmd`
-
-     #set -x
+    #set -x
 
     # try to submit the job three time in case it fails
     for i in {1..3}; do
         jobID=$($cmd 2>jobErr)
         jobErr=$(< jobErr); rm jobErr
 
-        #catch jobID jobErr '$cmd'
-        #echoerr id: .$jobID.
-        #echoerr err: .$jobErr.
         [ -z "$jobErr" ] || echo $jobErr >&2 
 
         # no error and a number job ID
@@ -991,42 +816,15 @@ if [[ "$testRun" == "run" ]]; then
     done
 
     #echoerr final output is: $jobID
-
-    #[ ! -z "$deps" ] && [[ "$jobID" =~ ^[0-9]+$ ]] && scontrol hold $jobID # todo: move this to sbatch command using -H
-
     #set +x
 
     #touch $submitFlag
 else
     jobID=$(date +"%4N")
-    #echoerr This is a testing, not really running a job...
     echoerr "This is testing, so no job is submitted. In real run it should submit job such as: Submitted batch job $jobID"
-    #jobID=
 fi
 
 echo -e "\n#myMem=$mem myTime=$time" >> $job
-
-# add this to the job script
-# echo -e "\n#Sbatch command output:\n#Submitted batch job $jobID" >> $job
-
-# if [ ! -z "$runningSingleJob" ]; then
-#     if [ -z "$out" ]; then
-#         touch $outFlag && ln -s $outFlag slurm-$jobID.out
-#     else
-#         out=${out/\%j/$jobID};
-#         touch $outFlag && ln -s $outFlag $out
-#     fi
-#     if [ ! -z "$err" ]; then
-#         err=${err/\%j/$jobID};
-#         touch $errFlag && ln -s $errFlag $err
-#     fi
-# fi
-
-#[ ! -z "$err" ] && ln -s $outFlag $err
-#if [ -z "$smartSlurmLogDir/" ]; then
-#    out=${out/\%j/$jobID};
-#    ln -s $job ${out/.out/}.sh
-#else
 
 #if [[ "$parentCmd" != */bin/snakemake* ]]; then
     printf "%-10s  %-20s  %-10s %-10s %-10s %-10s %-15s\n" $jobID $depsID $flag $program $ref $inputs>> $smartSlurmLogDir/allJobs.txt;
@@ -1040,5 +838,3 @@ echo Submitted batch job $jobID
 echoerr -e "Submitted batch job $jobID" 
 
 [ -z "$runningSingleJob" ] || echo -e "With mem: $mem and time: $time\nLog is appended .smartSlurm.log \nPlease search $current_date to find it.\n" >&2
-
-
